use_frameworks!

platform :ios, '12.0'

source 'https://cdn.cocoapods.org'

target 'SHMXTest_Example' do
  pod 'SHMXTest', path: '../', testspecs: ['Tests']
  pod 'SwiftLint', '~> 0.45.0'
  pod 'SwiftFormat/CLI', '~> 0.49.0'
end
