osx_image: xcode12.5
language: swift
# cache: cocoapods
podfile: Example/Podfile
 before_install:
 - bundle install
 - cd Example && bundle exec pod install
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SHMXTest.xcworkspace -scheme SHMXTest-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
